# Generated by Django 4.2.2 on 2023-07-19 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('salte', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_name',
            field=models.CharField(default='kunle_account', max_length=250, verbose_name='account name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='account_number',
            field=models.CharField(default=1862545, max_length=100, unique=True, verbose_name='account number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100, verbose_name='balance'),
        ),
        migrations.AddField(
            model_name='account',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='date of birth'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='passcode',
            field=models.IntegerField(default=46565, max_length=6, verbose_name='pass_code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='phone_number',
            field=models.CharField(default='0802344455', max_length=15, unique=True, verbose_name='phone number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
